import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import fs from 'node:fs';
import path from 'node:path';

// Public guides are real HTML, not hash routes or private analysis results.
function publicGuides() {
  let out;
  return {
    name: 'public-resume-guides',
    configResolved(c) { out = path.resolve(c.root, c.build.outDir); },
    closeBundle() {
      const base = 'https://hiresense-f3p6.onrender.com';
      const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
      const guides = [
        {slug:'resume-job-description-match',title:'Match your resume to a job description',description:'A practical guide to comparing your resume with a job description: required skills, evidence, missing keywords and truthful edits.',intro:'A resume works best when it makes the relevant evidence easy to find. Start with one real job description, not a generic list of keywords.',sections:[['Separate requirements from preferences','Make two lists from the job description: required qualifications and preferred experience. Keep responsibilities separate. A repeated skill can matter, but repetition alone does not tell you how the employer screens applicants.'],['Find evidence in your resume','For each requirement, find a project, job or qualification that supports it. Write down where that evidence appears. If there is no evidence, treat it as a gap rather than adding the skill to your resume.'],['Make relevant work easier to find','Move the strongest related project or bullet higher. Use the employer\'s terminology only where it accurately describes your work. Keep the result clear enough for a person to read, not just a keyword counter.'],['Use HireSense as a review aid','Upload a readable PDF and paste the job description, or try its posting URL. Review the match score, counted keywords and suggested edits. The score is a custom estimate, not a certified ATS result or an interview guarantee.']]},
        {slug:'resume-keywords',title:'Resume keywords without keyword stuffing',description:'Learn how to use job-description keywords honestly in resume skills and project bullets, without inventing experience or hiding text.',intro:'Useful keywords connect a job requirement to work you have actually done. A keyword list cannot replace that evidence.',sections:[['Choose specific terms','Look for named tools, languages, responsibilities and domain knowledge in the job description. Distinguish a technology you used from one you only read about. Avoid copying every word into your skills section.'],['Use keywords in context','A project bullet can explain what you built, the tool you used and the outcome. For example, mention MongoDB in the description of a real database task rather than repeating it across unrelated sections.'],['Do not hide or invent skills','Do not use white text, hidden keyword blocks or skills you cannot explain in an interview. Suggested rewrites still need your review. Keep only statements that are true for you.'],['Read the resume aloud','If a line sounds like a pile of terms, rewrite it as one clear sentence about your work. Compare it with the requirement again: does the line provide evidence, or merely repeat the phrase?']]},
        {slug:'resume-pdf-checklist',title:'Resume PDF checklist before upload',description:'Check text extraction, file size and resume readability before using HireSense. Supported input is a text PDF up to 4 MB and six pages.',intro:'A PDF that looks good on screen can still contain only an image. Check that its text can be selected and copied before uploading.',sections:[['Check that text is readable','Select a sentence in the PDF and copy it into a plain-text editor. If no text can be selected, export a new text PDF from the original document. HireSense does not perform OCR on image-only resumes.'],['Use supported input','HireSense accepts a PDF up to 4 MB and six pages. It also needs enough extractable text to review the resume. Keep your file within those limits and do not submit a password-protected document.'],['Check reading order','Copy several lines spanning headings and columns. If the order is confusing, simplify the layout and export again. The plain-text reading order should make the experience, dates and bullet points understandable.'],['Protect personal information','Remove information you do not need for a resume review. HireSense does not retain the uploaded PDF, but it stores extracted resume text, job text and results in your account for history and tailoring. You can delete analyses from History.']]},
        {slug:'tailor-resume',title:'Tailor a resume without inventing experience',description:'A step-by-step guide to tailoring a resume for one job while preserving truthful skills, project details and measurable outcomes.',intro:'Tailoring means choosing and explaining relevant evidence. It does not mean changing what you did to match an employer\'s wish list.',sections:[['Start from the original facts','Keep an original version of your resume. Mark the projects and experience relevant to this job. Preserve job titles, dates, qualifications and technologies you actually used.'],['Rewrite for clarity','Put the action, scope and result in a readable sentence. Use a real measurement where you have one. Never fill a suggested placeholder with a guessed percentage or made-up user count.'],['Review the tailored draft','HireSense can create an editable DOCX or PDF after an analysis. Read every line before sending it. Remove unsupported skills or statements, and confirm that ordering and emphasis still represent your work.'],['Compare and keep a version','Compare the tailored version with your original. Save it with the role or company name so you know which version you applied with. A better match estimate is not proof that you meet every requirement.']]},
        {slug:'job-posting-links',title:'Use a job posting URL or pasted description',description:'Understand HireSense job-link input, supported public posting pages and why some sites require pasting the job description instead.',intro:'HireSense accepts either a pasted job description or a job posting URL. A URL is convenient only when the page allows its text to be read.',sections:[['Use the exact job page','Paste the specific posting URL, not a search-results page or company homepage. Public Greenhouse and Lever postings are supported by the fetch flow; some other pages can also be readable. Availability depends on the source page.'],['Check the fetched text','The Fetch job text control lets you inspect and edit the result. Make sure the text is the right role and includes its requirements, not only navigation or a company summary.'],['Paste when a source blocks access','LinkedIn, Indeed, Naukri and Glassdoor are blocked by the application\'s fetch flow. Use your normal access to copy the description and paste it instead. Do not supply login credentials or attempt to bypass the site\'s controls.'],['Keep descriptions within limits','Use the relevant posting text. HireSense accepts a job description up to 12,000 characters and needs a meaningful description, not just a short job title. If you paste text and provide a link, the pasted description is used when it is long enough.']]},
        {slug:'match-score-explained',title:'What the HireSense match score means',description:'Understand the HireSense resume match score, keyword coverage and limitations. It is a review aid, not a certified ATS score or hiring prediction.',intro:'The match score summarizes one comparison between your resume and one job description. Use it to decide what to review, not whether an employer will hire you.',sections:[['How the score is calculated','HireSense combines two parts equally: keyword coverage counted in code and a model-generated fit estimate. The result is shown as a percentage and on a ten-point scale. Rewording or a different job description can change the result.'],['What keywords can tell you','Matched and missing terms help you inspect overlap with the posting. They do not establish depth of knowledge, years of experience or whether an employer\'s requirement is mandatory. Verify each important term against your actual evidence.'],['What it cannot promise','HireSense is not an employer\'s ATS and its score is not certified. No cutoff guarantees that your resume passes a first screen. Hiring also depends on the employer, applicant pool and requirements this comparison may not capture.'],['Choose the next useful action','Review missing requirements, formatting checks and weak bullets. Fix factual clarity first. Learn a genuinely missing skill or choose a more suitable role rather than adding unsupported terms just to raise a score.']]}
      ];
      const css=fs.readFileSync(new URL('./src/styles.css',import.meta.url),'utf8');
      const links=()=>`<div class="grid2">${guides.map(g=>`<article class="card"><h2><a href="/guides/${g.slug}/">${esc(g.title)}</a></h2><p>${esc(g.description)}</p></article>`).join('')}</div>`;
      const pages=[];
      const write=(url,title,description,body,crumbs)=>{
        const graph=[{'@type':'WebSite','@id':base+'/#website',name:'HireSense',url:base+'/'},{'@type':'WebPage',name:title,url:base+url,description,isPartOf:{'@id':base+'/#website'}},{'@type':'BreadcrumbList',itemListElement:crumbs.map(([u,n],i)=>({'@type':'ListItem',position:i+1,name:n,item:base+u}))}];
        const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | HireSense</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow"><link rel="canonical" href="${base+url}"><meta property="og:type" content="website"><meta property="og:site_name" content="HireSense"><meta property="og:title" content="${esc(title)} | HireSense"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${base+url}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${esc(title)} | HireSense"><meta name="twitter:description" content="${esc(description)}"><style>${css} .guide-intro{font-size:1.1rem}.guide-nav{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:24px;font-size:.9rem}.guide h2{margin-top:0}.guide{margin:20px 0}.grid2 h2{font-size:1.15rem}.guide li{margin:8px 0}</style><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':graph}).replace(/</g,'\\u003c')}</script></head><body><header class="nav"><a class="brand" href="/">Hire<span>Sense</span></a><nav><a href="/guides/">Resume guides</a><a href="/#/">Open app</a></nav></header><main class="wrap"><nav class="guide-nav" aria-label="Breadcrumb">${crumbs.map(([u,n])=>`<a href="${u}">${esc(n)}</a>`).join(' / ')}</nav>${body}<section class="card guide"><h2>Try the comparison in HireSense</h2><p>Create an account, upload your readable PDF, and provide the job description or posting URL. Review every suggestion before using it.</p><a class="btn" href="/#/">Open HireSense</a></section><h2>Related resume guides</h2>${links()}</main><footer class="foot">HireSense by Lakshya Yadav. Scores are custom estimates, not certified ATS results or hiring guarantees.</footer></body></html>`;
        const target=path.join(out,url,'index.html');fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,html);pages.push(base+url);
      };
      write('/guides/','Resume and job-match guides','Practical HireSense guides to resume keywords, readable PDFs, job posting links, truthful tailoring and match-score limitations.',`<h1>Resume and job-match guides</h1><p class="guide-intro">Learn how to compare a resume with one real job description, make honest edits and understand what the score can and cannot tell you. These guides are public and need no account.</p>`,[['/','Home'],['/guides/','Guides']]);
      for(const g of guides){const u='/guides/'+g.slug+'/';write(u,g.title,g.description,`<h1>${esc(g.title)}</h1><p class="guide-intro">${esc(g.intro)}</p>${g.sections.map(([h,p])=>`<section class="card guide"><h2>${esc(h)}</h2><p>${esc(p)}</p></section>`).join('')}`,[['/','Home'],['/guides/','Guides'],[u,g.title]]);}
      fs.writeFileSync(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${[base+'/',...pages].map(u=>`<url><loc>${u}</loc></url>`).join('')}</urlset>`);
      const index=path.join(out,'index.html');let html=fs.readFileSync(index,'utf8');html=html.replace('<div id="root"></div>',`<div id="root"><main style="font-family:system-ui;max-width:900px;margin:auto;padding:24px"><h1>HireSense - compare your resume with a job description</h1><p>Review keyword coverage, weak bullets and formatting. Match scores are custom estimates, not certified ATS scores or interview guarantees.</p><p><a href="/guides/">Read the public resume guides</a></p>${links()}<p>The ordering of evidence matters, but never add skills or achievements that are not true for you.</p></main></div>`);fs.writeFileSync(index,html);
      console.log(`[public-guides] Built ${pages.length} public guides; sitemap has ${pages.length+1} URLs`);
    }
  };
}
export default defineConfig({
  plugins: [react(), publicGuides()],
  server: { proxy: { '/api': 'http://localhost:3000' } }
});
